name: binaries
on:
  push:
    # Don't run on version tags (these are used for JS module).
    tags-ignore:
      - 'v**'
    branches:
      - '**'
    paths:
      - .github/workflows/binaries.yml
      - scripts/*
  schedule:
    - cron:  '0 0 * * 0'  # run each Sunday

env:
  ALPINE_BRANCH: v3.13
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JOBS: 3
  CFLAGS: -Os -fomit-frame-pointer -pipe
  LINUX_LDFLAGS: -static -Wl,--as-needed -Wl,-Map,linker.map
  DARWIN_LDFLAGS: -Wl,-map,linker.map
  WIN32_LDFLAGS: -Wl,--as-needed -Wl,-Map,linker.map
  # List of extra nginx modules to download.
  NGINX_MODULES: >-
    nginx/njs
    vision5/ngx_devel_kit
    openresty/echo-nginx-module
    openresty/headers-more-nginx-module
    openresty/set-misc-nginx-module

jobs:
  njs-multi-linux:
    name: njs-${{ matrix.NJS_VERSION }}${{ matrix.VARIANT }}-${{ matrix.ARCH }}-linux
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        NJS_VERSION:
          - 0.x.x
        VARIANT:
          - '-debug'
          - ''
        ARCH:
          - x86_64
          - aarch64
          - armv7
          - ppc64le
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Download and extract njs
        run: ./master/scripts/fetch-sources -d . nginx/njs@${{ matrix.NJS_VERSION }}

      - name: Download alpine-chroot-install
        run: |
          wget https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.13.0/alpine-chroot-install
          echo '444069f1a060b9f08b7e5ac264c8b9527b32fb54  alpine-chroot-install' | sha1sum -c
          chmod +x alpine-chroot-install

      - name: Install Alpine ${{ env.ALPINE_BRANCH }} for ${{ matrix.ARCH }}
        run: |
          sudo ./alpine-chroot-install \
            -a ${{ matrix.ARCH }} \
            -b ${{ env.ALPINE_BRANCH }} \
            -k 'VARIANT CFLAGS LDFLAGS JOBS' \
            -p 'build-base libedit-dev libedit-static pcre-dev ncurses-dev ncurses-static'
          /alpine/enter-chroot uname -a

      - name: Build njs
        env:
          VARIANT: ${{ matrix.VARIANT }}
          CFLAGS: ${{ env.CFLAGS }}
          LDFLAGS: ${{ env.LINUX_LDFLAGS }}
        run: |
          /alpine/enter-chroot -u $USER ./master/scripts/build-njs

      - name: Upload njs binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          path: artifact/*

  njs-x86_64-darwin:
    name: njs-${{ matrix.NJS_VERSION }}${{ matrix.VARIANT }}-x86_64-darwin
    runs-on: macos-latest
    strategy:
      matrix:
        NJS_VERSION:
          - 0.x.x
        VARIANT:
          - '-debug'
          - ''
    steps:
      - name: Install dependencies
        run: brew install jq libedit ncurses pcre

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Download and extract njs
        run: ./master/scripts/fetch-sources -d . nginx/njs@${{ matrix.NJS_VERSION }}

      # cmake prefers dynamic libs and there's no option to change it, so
      # we have to remove them to give it no other option than using static.
      - name: Remove dylibs
        run: |
          rm /usr/local/opt/libedit/lib/*.dylib
          rm /usr/local/opt/ncurses/lib/*.dylib
          rm /usr/local/opt/pcre/lib/*.dylib

      - name: Build njs
        env:
          VARIANT: ${{ matrix.VARIANT }}
          CFLAGS: ${{ env.CFLAGS }} -I/usr/local/opt/libedit/include -I/usr/local/opt/ncurses/include -I/usr/local/opt/pcre/include
          LDFLAGS: ${{ env.DARWIN_LDFLAGS }} -L/usr/local/opt/libedit/lib -L/usr/local/opt/ncurses/lib -L/usr/local/opt/pcre/lib
        run: ./master/scripts/build-njs

      - name: Upload njs binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          path: artifact/*

  nginx-multi-linux:
    name: nginx-${{ matrix.NGINX_VERSION }}-${{ matrix.ARCH }}-linux
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        NGINX_VERSION:
          - 1.18.x
          - 1.19.x
        ARCH:
          - x86_64
          - aarch64
          - armv7
          - ppc64le
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Download and extract nginx
        run: ./master/scripts/fetch-sources -d . nginx/nginx@release-${{ matrix.NGINX_VERSION }}

      - name: Download and extract nginx modules
        run: ./master/scripts/fetch-sources $NGINX_MODULES

      - name: Download alpine-chroot-install
        run: |
          wget https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.13.0/alpine-chroot-install
          echo '444069f1a060b9f08b7e5ac264c8b9527b32fb54  alpine-chroot-install' | sha1sum -c
          chmod +x alpine-chroot-install

      - name: Install Alpine ${{ env.ALPINE_BRANCH }} for ${{ matrix.ARCH }}
        run: |
          sudo ./alpine-chroot-install \
            -a ${{ matrix.ARCH }} \
            -b ${{ env.ALPINE_BRANCH }} \
            -k 'VARIANT NGINX_MODULES CFLAGS LDFLAGS JOBS' \
            -p 'build-base linux-headers openssl-dev openssl-libs-static pcre-dev zlib-dev zlib-static'
          /alpine/enter-chroot uname -a

      - name: Build nginx
        env:
          NGINX_MODULES: ${{ env.NGINX_MODULES }}
          VARIANT: ${{ matrix.VARIANT }}
          CFLAGS: ${{ env.CFLAGS }}
          LDFLAGS: ${{ env.LINUX_LDFLAGS }}
        run: |
          /alpine/enter-chroot -u $USER ./master/scripts/build-nginx

      - name: Upload nginx binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          path: artifact/*

  nginx-x86_64-darwin:
    name: nginx-${{ matrix.NGINX_VERSION }}-x86_64-darwin
    runs-on: macos-latest
    strategy:
      matrix:
        NGINX_VERSION:
          - 1.18.x
          - 1.19.x
    steps:
      - name: Install dependencies
        run: brew install jq openssl@1.1 pcre zlib

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Download and extract nginx
        run: ./master/scripts/fetch-sources -d . nginx/nginx@release-${{ matrix.NGINX_VERSION }}

      - name: Download and extract nginx modules
        run: ./master/scripts/fetch-sources $NGINX_MODULES

      # cmake prefers dynamic libs and there's no option to change it, so
      # we have to remove them to give it no other option than using static.
      - name: Remove dylibs
        run: |
          rm /usr/local/opt/openssl/lib/*.dylib
          rm /usr/local/opt/pcre/lib/*.dylib
          rm /usr/local/opt/zlib/lib/*.dylib

      - name: Build nginx
        env:
          NGINX_MODULES: ${{ env.NGINX_MODULES }}
          CFLAGS: ${{ env.CFLAGS }} -I/usr/local/opt/openssl/include -I/usr/local/opt/pcre/include -I/usr/local/opt/zlib/include
          LDFLAGS: ${{ env.DARWIN_LDFLAGS }} -L/usr/local/opt/openssl/lib -L/usr/local/opt/pcre/lib -L/usr/local/opt/zlib/lib
        run: ./master/scripts/build-nginx

      - name: Upload nginx binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          path: artifact/*

  nginx-x86_64-win32:
    name: nginx-${{ matrix.NGINX_VERSION }}-x86_64-win32
    runs-on: windows-latest
    strategy:
      matrix:
        NGINX_VERSION:
          - 1.18.x
          - 1.19.x
    steps:
      - name: Remove nginx/njs from NGINX_MODULES (not supported on Windows)
        shell: bash
        run: echo NGINX_MODULES=$(printf '%s\n' $NGINX_MODULES | grep -xv nginx/njs) >> $GITHUB_ENV

      - name: Setup MSYS2 and install packages
        uses: msys2/setup-msys2@v2
        with:
          update: false
          install: base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-jq

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Download and extract nginx
        shell: msys2 {0}
        run: ./master/scripts/fetch-sources -d . nginx/nginx@release-${{ matrix.NGINX_VERSION }}

      - name: Download and extract nginx MSYS2 patches
        shell: msys2 {0}
        run: ./master/scripts/fetch-sources -d msys2 "myfreeer/nginx-build-msys2@1.18.0"

      - name: Download and extract nginx modules
        shell: msys2 {0}
        run: ./master/scripts/fetch-sources $NGINX_MODULES

      - name: Download and extract libraries
        shell: msys2 {0}
        run: ./master/scripts/fetch-sources 'openssl@1.1.x[a-z]' 'pcre@8.x' 'madler/zlib@v1.2.x'

      - name: Apply patches
        shell: msys2 {0}
        run: |
          for i in msys2/nginx-*.patch; do
            patch -p1 < $i
          done

      - name: Build nginx
        shell: msys2 {0}
        env:
          NGINX_MODULES: ${{ env.NGINX_MODULES }}
          # -DFD_SETSIZE=1024 is per official nginx win32 binary.
          CFLAGS: ${{ env.CFLAGS }} -DFD_SETSIZE=1024
          LDFLAGS: ${{ env.WIN32_LDFLAGS }}
        run: ./master/scripts/build-nginx

      - name: Upload nginx binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          path: artifact/*

  upload:
    name: Upload binaries
    needs:
      - njs-multi-linux
      - njs-x86_64-darwin
      - nginx-multi-linux
      - nginx-x86_64-darwin
      - nginx-x86_64-win32
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    container:
      image: docker://alpine:3.13
    steps:
      - name: Install dependencies
        run: apk add -U git nodejs tree

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Checkout binaries branch
        uses: actions/checkout@v2
        with:
          ref: binaries
          path: binaries

      - name: Download and unpack all workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Move downloaded binaries into repository
        run: |
          mv artifact/* binaries/
          ls -lah binaries/

      - name: Generate index.json
        run: ./master/scripts/generate-index --json binaries/ binaries/index.json

      - name: Generate index.csv
        run: ./master/scripts/generate-index --csv binaries/ binaries/index.csv

      - name: Generate index.html
        working-directory: binaries
        run: tree -hv -H . -o index.html .

      - name: Check if there are any changes
        id: has_changes
        working-directory: binaries
        run: |
          git status || exit 1
          test -n "$(git status --porcelain)" && result=yes || result=no
          echo ::set-output name=result::$result

      - name: Commit changes
        if: steps.has_changes.outputs.result == 'yes'
        working-directory: binaries
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Built from ${{ github.sha }}"

      - name: Push changes back to origin
        if: steps.has_changes.outputs.result == 'yes'
        working-directory: binaries
        run: git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git binaries
